export const FEATURE_LAYER_DETAILS_REQUEST = 'FEATURE_LAYER_DETAILS_REQUEST';
export const FEATURE_LAYER_DETAILS_SUCCESS = 'FEATURE_LAYER_DETAILS_SUCCESS';
export const FEATURE_LAYER_DETAILS_FAIL = 'FEATURE_LAYER_DETAILS_FAIL';
export const FEATURE_LAYER_DETAILS_RESET = 'FEATURE_LAYER_DETAILS_RESET';


export const ADD_LAYER_TO_MAP_REQUEST = 'ADD_LAYER_TO_MAP_REQUEST';
export const ADD_LAYER_TO_MAP_SUCCESS = 'ADD_LAYER_TO_MAP_SUCCESS';
export const ADD_LAYER_TO_MAP_FAIL = 'ADD_LAYER_TO_MAP_FAIL';
export const ADD_LAYER_TO_MAP_RESET = 'ADD_LAYER_TO_MAP_RESET';