export const FEATURE_LAYER_DETAILS_REQUEST = 'FEATURE_LAYER_DETAILS_REQUEST';
export const FEATURE_LAYER_DETAILS_SUCCESS = 'FEATURE_LAYER_DETAILS_SUCCESS';
export const FEATURE_LAYER_DETAILS_FAIL = 'FEATURE_LAYER_DETAILS_FAIL';
export const FEATURE_LAYER_DETAILS_RESET = 'FEATURE_LAYER_DETAILS_RESET';

export const FEATURE_LAYER_CREATE_REQUEST = 'FEATURE_LAYER_CREATE_REQUEST';
export const FEATURE_LAYER_CREATE_SUCCESS = 'FEATURE_LAYER_CREATE_SUCCESS';
export const FEATURE_LAYER_CREATE_FAIL = 'FEATURE_LAYER_CREATE_FAIL';

export const LIST_FEATURE_LAYER_REQUEST = 'LIST_FEATURE_LAYER_REQUEST';
export const LIST_FEATURE_LAYER_SUCCESS = 'LIST_FEATURE_LAYER_SUCCESS';
export const LIST_FEATURE_LAYER_FAIL = 'LIST_FEATURE_LAYER_FAIL';
export const LIST_FEATURE_LAYER_RESET = 'LIST_FEATURE_LAYER_RESET';


export const FEATURE_LAYER_UPDATE_REQUEST = 'FEATURE_LAYER_UPDATE_REQUEST';
export const FEATURE_LAYER_UPDATE_SUCCESS = 'FEATURE_LAYER_UPDATE_SUCCESS';
export const FEATURE_LAYER_UPDATE_FAIL = 'FEATURE_LAYER_UPDATE_FAIL';
export const FEATURE_LAYER_UPDATE_RESET = 'FEATURE_LAYER_UPDATE_RESET';


export const ADD_LAYER_TO_MAP_REQUEST = 'ADD_LAYER_TO_MAP_REQUEST';
export const ADD_LAYER_TO_MAP_SUCCESS = 'ADD_LAYER_TO_MAP_SUCCESS';
export const ADD_LAYER_TO_MAP_FAIL = 'ADD_LAYER_TO_MAP_FAIL';
export const ADD_LAYER_TO_MAP_RESET = 'ADD_LAYER_TO_MAP_RESET';

